name: Test Docker Services

on:
  push:
    branches:
      - main

jobs:
  test-docker-services:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.13-management
        ports:
          - 5672:5672
          - 15672:15672
        options: --health-cmd "rabbitmqctl status" --health-interval 15s --health-retries 10

      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

      clamav:
        image: clamav/clamav:1.0
        options: --health-cmd "clamdscan --version" --health-interval 15s --health-retries 5

      gotenberg:
        image: thecodingmachine/gotenberg:7.10.2
        ports:
          - 3000:3000

      thumbor:
        image: apsl/thumbor:6.7.5
        ports:
          - 8000:8000

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Wait for RabbitMQ to be ready
        run: |
          for i in {1..20}; do
            if nc -z localhost 5672; then
              echo "RabbitMQ is ready!"
              break
            fi
            echo "Waiting for RabbitMQ..."
            sleep 5
          done

      - name: Print RabbitMQ logs
        if: failure()
        run: docker logs rabbitmq

      - name: Verify Services
        run: |
          curl -f http://localhost:15672 || echo "RabbitMQ management UI not accessible"
          curl -f http://localhost:3000 || echo "Gotenberg service not accessible"
          curl -f http://localhost:8000 || echo "Thumbor service not accessible"
